// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGlds
{
        public const string achievement_hight_school = "CgkIhNOd2YYLEAIQBQ"; // <GPGSID>
        public const string achievement_college = "CgkIhNOd2YYLEAIQBg"; // <GPGSID>
        public const string achievement_junior_high_school = "CgkIhNOd2YYLEAIQBA"; // <GPGSID>
        public const string leaderboard_brain_training_puzzle = "CgkIhNOd2YYLEAIQAA"; // <GPGSID>
        public const string achievement_professor = "CgkIhNOd2YYLEAIQBw"; // <GPGSID>
        public const string achievement_elementary_school = "CgkIhNOd2YYLEAIQAw"; // <GPGSID>

}

